spring:
  application:
    name: ${SPRING_APPLICATION_NAME:student-career}

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongodb:27017/student_career}
      username: ${SPRING_DATA_MONGODB_USERNAME:}
      password: ${SPRING_DATA_MONGODB_PASSWORD:}

  jackson:
    serialization:
      indent_output: ${SPRING_JACKSON_SERIALIZATION_INDENT_OUTPUT:true}
    default-property-inclusion: ${SPRING_JACKSON_DEFAULT_PROPERTY_INCLUSION:non_null}

server:
  port: ${SERVER_PORT:8080}

security:
  enabled: ${SECURITY_ENABLED:true}

logging:
  level:
    org.springframework.security: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY:INFO}
    org.springframework.data.mongodb.core.MongoTemplate: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA_MONGODB_CORE_MONGOTEMPLATE:DEBUG}

export:
  anonymization:
    salt: ${EXPORT_ANONYMIZATION_SALT:student-career-secret-2025}
